language: objective-c

osx_image: xcode8.1

xcode_project: Apollo.xcodeproj

matrix:
  include:
  - xcode_scheme: Apollo iOS
    xcode_sdk: iphonesimulator10.1
    env: DESTINATION="platform=iOS Simulator,OS=10.1,name=iPhone 7"
  - xcode_scheme: Apollo iOS
    xcode_sdk: iphonesimulator10.1
    env: DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s"
  - xcode_scheme: Apollo macOS
    xcode_sdk: macosx10.12
    env: DESTINATION="platform=macOS,arch=x86_64"

cache:
  directories:
    - ../starwars-server

before_install:
  - (./scripts/install-or-update-starwars-server.sh)
  - (cd ../starwars-server && npm start) &
  - npm install -g apollo-codegen

script:
  - set -o pipefail
  - xcodebuild clean build test -project "${TRAVIS_XCODE_PROJECT}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${DESTINATION}" | xcpretty
